baseURL = 'https://alfredohuitron.com/'
googleAnalytics = "G-VLCJR0XGX9"
languageCode = 'en-us'
title = 'Alfredo Huitron'
theme = "blog-theme"
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Writing"
    url = "/writing/"
    weight = 2
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3
  [[menu.main]]
    name = "Reads"
    url = "/reads/"
    weight = 4